# 출력 문자열
text:

  # PlaceholderAPI
  papi:

    # %discordauth_auth%
    auth:

      # 인증됨
      true: "&a✔"

      # 인증되지 않음
      false: "&c✗"


# 인증 설정
auth:

  # 인증 코드 만료 기간 (초)
  codeExpirationTime: 60

  # 미인증시 움직임, 블럭 파괴/설치 방지
  cancellationAction: true

  # 인증시 닉네임 변경
  # {discordTag} : 디스코드 계정의 Tag
  # {playerName} : 마인크래프트 계정의 이름
  # {playerId} : 마인크래프트 계정의 UUID
  changeNickname: "[ {playerName} ]"


  # 미인증시 활동 제한
  block:

    # 명령어
    command: true

    # 채팅
    chat: true

    # 상호작용
    interact: true

    # 움직임
    move: true


  # 인증 요구 타이틀
  authRequestTitle:

    # 활성화 여부
    enable: true

    # 메인 타이틀
    title: "&8[&6/인증&8]"

    # 서브 타이틀
    subTitle: "&7인증을 해주세요!"

    # 페이드 인
    fadeIn: 1

    # 유지
    stay: 3

    # 페이드 아웃
    fadeOut: 1


    # 표시 간격
    interval: 10


  # 인증 로비
  # 인증 미완료시 설정된 위치로 텔레포트 됩니다.
  verifyLobby:

    # 활성화 여부
    enable: true

    # 이동 전 지연시간
    delay: 10

    # 위치
    location:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0

  # 로비
  # 인증 완료시 설정된 위치로 텔레포트 됩니다.
  lobby:

    # 활성화 여부
    enable: true

    # 이동 전 지연시간
    delay: 10

    # 위치
    location:
      world: world
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0