name: ST-DiscordAuth
main: net.starly.discordauth.DiscordAuthMain
author: Starly Team
website: http://starly.kr/discord

description: DiscordAuth Plugin.

softdepend:
  - ST-Core
  - PlaceholderAPI

version: 1.2.5
api-version: 1.13

commands:
  discord-auth:
      aliases: [ da, 디코연동, 연동, 인증 ]